---

- name: Systemd | Create Init script for services
  template:
    src: service.j2
    dest: "{{ initscripts_path }}/{{ item.value.file_name }}"
    mode: 0751
    force: yes
  become: yes
  with_dict: "{{ services }}"

- name: System Users | Change Init script ownership
  file:
    path: "{{ initscripts_path }}/{{ item.value.file_name }}"
    owner: "{{ item.value.user }}"
    group: "{{ kafka_system_users.group }}"
    force: yes
  become: yes
  with_dict: "{{ services }}"
  when: kafka_system_users.enabled

- block:
  - name: JVM | Render environment file from kafka-jvm.sh template
    template:
      src: kafka-jvm.sh.j2
      dest: /etc/profile.d/kafka-jvm.sh
      force: yes

  - name: System Users | Change environment file ownership
    file:
      path: /etc/profile.d/kafka-jvm.sh
      owner: "kafka"
      mode: 0751
      group: "{{ kafka_system_users.group }}"
      force: yes
    when:
    - kafka_system_users.enabled

  when: inventory_hostname in groups['kafka']

- name: Systemd | Create services unit
  become: yes
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ item.value.file_name }}.service"
    mode: 0640
    force: yes
  with_dict: "{{ services }}"

- name: System Users | Change service unit ownership
  file:
    path: "/etc/systemd/system/{{ item.value.file_name }}.service"
    mode: 0640
    group: "{{ kafka_system_users.group }}"
    force: yes
  with_dict: "{{ services }}"
  when: kafka_system_users.enabled

- name: Systemd | Reload daemon
  systemd:
    daemon_reload: yes

- name: Systemd | Configure service
  systemd:
    name: "{{ item.value.file_name }}"
    state: "{{ item.value.state | default('started') }}"
    enabled: "{{ item.value.enabled | default(true) }}"
  with_dict: "{{ services }}"
  register: result
  until: result is succeeded
  retries: 3
  ignore_errors: yes
